const SERVER_URL = 'http://localhost:8880';
const DEFAULT_VOICE = 'af_bella';
const DEFAULT_SPEED = 1.0;
const CHUNK_TARGET_LENGTH = 300;
const CHUNK_MIN_LENGTH = 100;
const CHUNK_MAX_LENGTH = 500;
const KEEPALIVE_ALARM_NAME = 'kokoro-keepalive';
const KEEPALIVE_INTERVAL_MINUTES = 0.4;

const MSG = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  STOP: 'STOP',
  EXTRACT_TEXT: 'EXTRACT_TEXT',
  TEXT_EXTRACTED: 'TEXT_EXTRACTED',
  CHUNK_READY: 'CHUNK_READY',
  CHUNK_FINISHED: 'CHUNK_FINISHED',
  STATUS_UPDATE: 'STATUS_UPDATE',
  SERVER_STATUS: 'SERVER_STATUS',
  ERROR: 'ERROR',
};

const STATUS = {
  IDLE: 'idle',
  EXTRACTING: 'extracting',
  LOADING: 'loading',
  PLAYING: 'playing',
  PAUSED: 'paused',
  ERROR: 'error',
};

export {
  SERVER_URL,
  DEFAULT_VOICE,
  DEFAULT_SPEED,
  CHUNK_TARGET_LENGTH,
  CHUNK_MIN_LENGTH,
  CHUNK_MAX_LENGTH,
  KEEPALIVE_ALARM_NAME,
  KEEPALIVE_INTERVAL_MINUTES,
  MSG,
  STATUS,
};
