const SERVER_URL = 'http://localhost:8880';
const CLOUD_SERVER_URL = 'https://api.speakademic.com';
const DEFAULT_VOICE = 'af_bella';
const DEFAULT_SPEED = 1.0;

const TTS_MODE = {
  LOCAL: 'local',
  CLOUD: 'cloud',
};
const CHUNK_TARGET_LENGTH = 300;
const CHUNK_MIN_LENGTH = 100;
const CHUNK_MAX_LENGTH = 500;
const KEEPALIVE_ALARM_NAME = 'speakademic-keepalive';
const KEEPALIVE_INTERVAL_MINUTES = 0.4;
const SPEED_OPTIONS = [0.75, 1.0, 1.25, 1.5, 1.75, 2.0];
const POSITION_SAVE_INTERVAL_MS = 5000;
const SERVER_RETRY_INTERVAL_MS = 5000;
const SERVER_RETRY_MAX_ATTEMPTS = 12;
const PREFETCH_BUFFER_SIZE = 3;
const ADAPTIVE_SLOW_RATIO = 0.5;
const ADAPTIVE_MIN_CHUNK = 150;
const ADAPTIVE_MAX_CHUNK = 600;

const EQUATIONEER_URL = 'http://localhost:8000';

const EQUATION_MODE = {
  SKIP: 'skip',
  EXPLAIN: 'explain',
};

const MSG = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  STOP: 'STOP',
  EXTRACT_TEXT: 'EXTRACT_TEXT',
  TEXT_EXTRACTED: 'TEXT_EXTRACTED',
  CHUNK_READY: 'CHUNK_READY',
  CHUNK_FINISHED: 'CHUNK_FINISHED',
  SKIP_FORWARD: 'SKIP_FORWARD',
  SKIP_BACK: 'SKIP_BACK',
  SET_SPEED: 'SET_SPEED',
  SET_VOICE: 'SET_VOICE',
  GET_VOICES: 'GET_VOICES',
  JUMP_TO_SECTION: 'JUMP_TO_SECTION',
  RESUME_PROMPT: 'RESUME_PROMPT',
  RESUME_ACCEPT: 'RESUME_ACCEPT',
  RESUME_DECLINE: 'RESUME_DECLINE',
  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  HEARTBEAT: 'HEARTBEAT',
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  STATUS_UPDATE: 'STATUS_UPDATE',
  SERVER_STATUS: 'SERVER_STATUS',
  ERROR: 'ERROR',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  AUTH_STATE: 'AUTH_STATE',
  SUBSCRIPTION_STATUS: 'SUBSCRIPTION_STATUS',
  UPGRADE: 'UPGRADE',
  MANAGE_SUBSCRIPTION: 'MANAGE_SUBSCRIPTION',
  SET_TTS_MODE: 'SET_TTS_MODE',
};

const STATUS = {
  IDLE: 'idle',
  EXTRACTING: 'extracting',
  LOADING: 'loading',
  PLAYING: 'playing',
  PAUSED: 'paused',
  ERROR: 'error',
};

export {
  SERVER_URL,
  CLOUD_SERVER_URL,
  EQUATIONEER_URL,
  TTS_MODE,
  EQUATION_MODE,
  DEFAULT_VOICE,
  DEFAULT_SPEED,
  CHUNK_TARGET_LENGTH,
  CHUNK_MIN_LENGTH,
  CHUNK_MAX_LENGTH,
  KEEPALIVE_ALARM_NAME,
  KEEPALIVE_INTERVAL_MINUTES,
  SPEED_OPTIONS,
  POSITION_SAVE_INTERVAL_MS,
  SERVER_RETRY_INTERVAL_MS,
  SERVER_RETRY_MAX_ATTEMPTS,
  PREFETCH_BUFFER_SIZE,
  ADAPTIVE_SLOW_RATIO,
  ADAPTIVE_MIN_CHUNK,
  ADAPTIVE_MAX_CHUNK,
  MSG,
  STATUS,
};
